#!/bin/bash

env=$1
port=$(/Users/tboudreaux/Programing/condaZSH/cjupyter_get_port.py $env)

if [[ "$port" -eq "$port" ]] 2>/dev/null; then
	killing=$(jupyter notebook stop $port)
else
	echo $port
fi
