#!/bin/bash

function get_envs()
{
    env_string=$(ls /anaconda/envs/)
    env_list=$(echo $env_string | tr " " "\n")
}


get_envs
PID=$(ps | grep jupyter | grep -v "grep" | grep -v "cjupyterstop" | grep -v "cjupyter.py" | grep -v "debug");
i=0;
for word in $PID
do
	for env in $env_list
	do
		if [[ $env == $word  ]]; then
			echo $word
			i=1+$i
		fi
	done
done
ROOTPID=$(ps aux | grep //anaconda/bin/jupyter-lab | grep -v "grep");
if [[ $ROOTPID != ""  ]]; then
	echo "root"
fi
